name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: 'Windows 32'
            output: 'libtesseract32.dll'
            cmake_args: '-G "Visual Studio 16 2019" -A Win32'
            sw_args: '-platform x86 -win-mt'

          - os: windows-latest
            name: 'Windows 64'
            output: 'libtesseract64.dll'
            cmake_args: '-G "Visual Studio 16 2019"'
            sw_args: '-platform x64 -win-mt'

          - os: ubuntu-20.04
            name: 'Linux 64'
            output: 'libtesseract64.so'
            cmake_args: '-G "Unix Makefiles"'
            sw_args: '-platform x64'
            
          - os: macos-latest
            name: 'MacOS 64'
            output: 'libtesseract64.dylib'
            cmake_args: '-G "Unix Makefiles"'
            sw_args: '-platform x64 -os macos-10.13'

    steps:
      - uses: actions/checkout@v2.3.4
        with:  
          submodules: true
      
      - uses: egorpugin/sw-action@master
      
      - name: Cache
        id: cache
        uses: actions/cache@v2.1.5
        with:
          path: storage
          key: ${{ matrix.config.os }}${{ matrix.config.sw_args }}

      - name: Build Tesseract
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./sw build ${{ matrix.config.sw_args }} -storage-dir=storage -static -static-dependencies -config r org.sw.demo.google.tesseract.tesseract-master
          
      - name: Extract Headers & Libraries
        continue-on-error: true
        run: |
          mkdir -p libs
          mkdir -p headers/tesseract
          mkdir -p headers/leptonica
          
          find "storage/pkg/" -name "*.a" -exec cp "{}" "libs" \;
          find "storage/pkg/" -name "*.lib" -exec cp "{}" "libs" \;
          
          tesseract=$(find "storage/pkg/" -name "baseapi.h" -exec dirname {} \; -quit)
          find "$tesseract" -name "*.h*" -exec cp "{}" headers/tesseract/ \;
          find "storage/pkg/" -wholename "*tesseract/version.h" -exec cp "{}" headers/tesseract/ \;
          
          leptonica=$(find "storage/pkg/" -name "*leptonica*" -exec dirname {} \; -quit)/../../../../
          find "$leptonica" -name "*.h" -exec cp "{}" headers/leptonica/ \;
          
          # Delete crap that causes linking errors
          rm libs/*xxHash*
          rm libs/*boost.thread*

      - name: Build Plugin
        continue-on-error: true
        run: |
          cmake -S . ${{ matrix.config.cmake_args }}
          cmake --build .  --config Release
          find . -name libtesseract.binary -exec cp "{}" ${{ matrix.config.output }} \;

      - uses: actions/upload-artifact@v2.2.3
        with:
          path: ${{ matrix.config.output }}